
[functions.approve-data-room]
enabled = true
verify_jwt = true
import_map = "./functions/approve-data-room/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/approve-data-room/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/approve-data-room/*.html" ]

[functions.notify-founder]
enabled = true
verify_jwt = true
import_map = "./functions/notify-founder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-founder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-founder/*.html" ]

[functions.initialize-payment]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-payment/*.html" ]

[functions.paystack-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-webhook/*.html" ]

[functions.welcome-email]
enabled = true
verify_jwt = true
import_map = "./functions/welcome-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/welcome-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/welcome-email/*.html" ]

[functions.create-subaccount]
enabled = true
verify_jwt = true
import_map = "./functions/create-subaccount/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-subaccount/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-subaccount/*.html" ]

[functions.initialize-support]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-support/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-support/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-support/*.html" ]

[functions.support-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/support-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/support-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/support-webhook/*.html" ]

[functions.crm-data]
enabled = true
verify_jwt = true
import_map = "./functions/crm-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-data/*.html" ]

[functions.webhook-router]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-router/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-router/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-router/*.html" ]

[functions.crm-users]
enabled = true
verify_jwt = true
import_map = "./functions/crm-users/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-users/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-users/*.html" ]

[functions.crm-finance]
enabled = true
verify_jwt = true
import_map = "./functions/crm-finance/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-finance/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-finance/*.html" ]

[functions.crm-toggle-live]
enabled = true
verify_jwt = true
import_map = "./functions/crm-toggle-live/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-toggle-live/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-toggle-live/*.html" ]

[functions.backfill-payments]
enabled = true
verify_jwt = true
import_map = "./functions/backfill-payments/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/backfill-payments/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/backfill-payments/*.html" ]

[functions.crm-broadcast]
enabled = true
verify_jwt = true
import_map = "./functions/crm-broadcast/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-broadcast/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-broadcast/*.html" ]

[functions.notify-opportunity]
enabled = true
verify_jwt = true
import_map = "./functions/notify-opportunity/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-opportunity/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-opportunity/*.html" ]

[functions.waitlist-broadcast]
enabled = true
verify_jwt = true
import_map = "./functions/waitlist-broadcast/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/waitlist-broadcast/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/waitlist-broadcast/*.html" ]

[functions.send-team-invite]
enabled = true
verify_jwt = true
import_map = "./functions/send-team-invite/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-team-invite/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-team-invite/*.html" ]

[functions.decline-data-room]
enabled = true
verify_jwt = true
import_map = "./functions/decline-data-room/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/decline-data-room/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/decline-data-room/*.html" ]

[functions.initialize-teams-upgrade]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-teams-upgrade/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-teams-upgrade/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-teams-upgrade/*.html" ]

[functions.teams-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/teams-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/teams-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/teams-webhook/*.html" ]

[functions.initialize-incorporation-payment]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-incorporation-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-incorporation-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-incorporation-payment/*.html" ]

[functions.incorporation-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/incorporation-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/incorporation-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/incorporation-webhook/*.html" ]

[functions.verify-fireside-slug]
enabled = true
verify_jwt = true
import_map = "./functions/verify-fireside-slug/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-fireside-slug/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-fireside-slug/*.html" ]
